Saffron UK import data: 2019 - 2023 provided by: https://wits.worldbank.org/trade/comtrade/en/country/GBR/year/2022/tradeflow/Imports/partner/ALL/product/091020

In [1]:
import pandas as pd

uk_import_path_2019 = "./uk-imports-data/uk-import-2019.xlsx"
uk_import_path_2020 = "./uk-imports-data/uk-import-2020.xlsx"
uk_import_path_2021 = "./uk-imports-data/uk-import-2021.xlsx"
uk_import_path_2022 = "./uk-imports-data/uk-import-2022.xlsx"
uk_import_path_2023 = "./uk-imports-data/uk-import-2023.xlsx"

imports_2019 = pd.ExcelFile(uk_import_path_2019)
imports_2020 = pd.ExcelFile(uk_import_path_2020)
imports_2021 = pd.ExcelFile(uk_import_path_2021)
imports_2022 = pd.ExcelFile(uk_import_path_2022)
imports_2023 = pd.ExcelFile(uk_import_path_2023)

dfs_19 = {sheet_name: imports_2019.parse(sheet_name) 
          for sheet_name in imports_2019.sheet_names}

dfs_20 = {sheet_name: imports_2020.parse(sheet_name) 
          for sheet_name in imports_2020.sheet_names}

dfs_21 = {sheet_name: imports_2021.parse(sheet_name) 
          for sheet_name in imports_2021.sheet_names}

dfs_22 = {sheet_name: imports_2022.parse(sheet_name) 
          for sheet_name in imports_2022.sheet_names}

dfs_23 = {sheet_name: imports_2023.parse(sheet_name) 
          for sheet_name in imports_2023.sheet_names}


data_19 = dfs_19["By-HS6Product"]
data_20 = dfs_20["By-HS6Product"]
data_21 = dfs_21["By-HS6Product"]
data_22 = dfs_22["By-HS6Product"]
data_23 = dfs_23["By-HS6Product"]

In [2]:
data_19 = pd.DataFrame(data_19,
                  columns=['Reporter', 'TradeFlow', 'ProductCode', 'Product Description', 'Year', 'Partner', 'Trade Value 1000USD', 'Quantity', 'Quantity Unit'])

data_19 = data_19.drop(columns=["Reporter", "TradeFlow", "ProductCode", "Product Description", "Quantity Unit"])

data_20 = pd.DataFrame(data_20,
                  columns=['Reporter', 'TradeFlow', 'ProductCode', 'Product Description', 'Year', 'Partner', 'Trade Value 1000USD', 'Quantity', 'Quantity Unit'])

data_20 = data_20.drop(columns=["Reporter", "TradeFlow", "ProductCode", "Product Description", "Quantity Unit"])

data_21 = pd.DataFrame(data_21,
                  columns=['Reporter', 'TradeFlow', 'ProductCode', 'Product Description', 'Year', 'Partner', 'Trade Value 1000USD', 'Quantity', 'Quantity Unit'])

data_21 = data_21.drop(columns=["Reporter", "TradeFlow", "ProductCode", "Product Description", "Quantity Unit"])

data_22 = pd.DataFrame(data_22,
                  columns=['Reporter', 'TradeFlow', 'ProductCode', 'Product Description', 'Year', 'Partner', 'Trade Value 1000USD', 'Quantity', 'Quantity Unit'])

data_22 = data_22.drop(columns=["Reporter", "TradeFlow", "ProductCode", "Product Description", "Quantity Unit"])

data_23 = pd.DataFrame(data_23,
                  columns=['Reporter', 'TradeFlow', 'ProductCode', 'Product Description', 'Year', 'Partner', 'Trade Value 1000USD', 'Quantity', 'Quantity Unit'])

data_23 = data_23.drop(columns=["Reporter", "TradeFlow", "ProductCode", "Product Description", "Quantity Unit"])

data_19 = data_19.rename(columns={"Partner": "From", "Trade Value 1000USD": "value"})
data_20 = data_20.rename(columns={"Partner": "From", "Trade Value 1000USD": "value"})
data_21 = data_21.rename(columns={"Partner": "From", "Trade Value 1000USD": "value"})
data_22 = data_22.rename(columns={"Partner": "From", "Trade Value 1000USD": "value"})
data_23 = data_23.rename(columns={"Partner": "From", "Trade Value 1000USD": "value"})

In [3]:
data_19["value"] = 1000 * data_19["value"]
data_20["value"] = 1000 * data_20["value"]
data_21["value"] = 1000 * data_21["value"]
data_22["value"] = 1000 * data_22["value"]
data_23["value"] = 1000 * data_23["value"]

In [ ]:
data_23['Cost_per_kg'] = data_23['value'] / data_23['Quantity']
data_23

In [ ]:
path = "./uk-imports-data/country_hsproduct2digit_year.dta"
df = pd.read_stata(path)
df

Dataframe by baci: https://www.cepii.fr/CEPII/en/bdd_modele/bdd_modele_item.asp?id=37 HS22 (2022), functions below only obtain saffron for uk

In [97]:
def map_country_codes(country_codes_path):
    country_codes_df = pd.read_csv(country_codes_path)
    country_codes_map = {}

    for _, r in country_codes_df.iterrows():
        country_codes_map[r["country_code"]] = r["country_name"]
    
    return country_codes_map

def get_saffron_imports(data_path, country_codes_map):
    df_baci = pd.read_csv(data_path)

    df_baci.rename(columns={"t": "year", "i": "exporter", "j": "importer", "k": "product", "v": "value", "q": "quantity"}, inplace=True)

    saffron_data = df_baci[df_baci['product'] == 91020] #saffron code is 91020
    saffron_data_uk = saffron_data[saffron_data['importer'] == 826] #uk code 826

    for i, r in saffron_data_uk.iterrows():
        saffron_data_uk.at[i, "exporter"] = country_codes_map[r["exporter"]]
    
    return saffron_data_uk

In [ ]:
country_codes_path = "./baci_data/country_codes_V202401b.csv"
country_codes_map = map_country_codes(country_codes_path)

path_baci_2022 = "./baci_data/HS17/BACI_HS17_Y2022_V202401b.csv"
path_baci_2021 = "./baci_data/HS17/BACI_HS17_Y2021_V202401b.csv"
path_baci_2020 = "./baci_data/HS17/BACI_HS17_Y2020_V202401b.csv"
path_baci_2019 = "./baci_data/HS17/BACI_HS17_Y2019_V202401b.csv"
path_baci_2018 = "./baci_data/HS17/BACI_HS17_Y2018_V202401b.csv"
path_baci_2017 = "./baci_data/HS17/BACI_HS17_Y2017_V202401b.csv"

data_saffron_uk_2022 = get_saffron_imports(path_baci_2022, country_codes_map)
data_saffron_uk_2021 = get_saffron_imports(path_baci_2021, country_codes_map)
data_saffron_uk_2020 = get_saffron_imports(path_baci_2020, country_codes_map)
data_saffron_uk_2019 = get_saffron_imports(path_baci_2019, country_codes_map)
data_saffron_uk_2018 = get_saffron_imports(path_baci_2018, country_codes_map)
data_saffron_uk_2017 = get_saffron_imports(path_baci_2017, country_codes_map)

Raw export data into UK, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [101]:
data_saffron_uk_2022

year              exporter  importer  product     value  \
5197      2022           Afghanistan       826    91020   216.225   
446153    2022               Austria       826    91020    24.543   
477852    2022               Bahrain       826    91020     0.064   
801746    2022               Belgium       826    91020     2.891   
1016615   2022                Brazil       826    91020     0.468   
1452321   2022             Sri Lanka       826    91020     0.276   
2010462   2022                 China       826    91020     5.842   
2595440   2022               Denmark       826    91020     2.797   
3247517   2022                France       826    91020   605.306   
3684513   2022               Germany       826    91020    29.832   
3822296   2022                Greece       826    91020   132.593   
4156318   2022               Hungary       826    91020     0.006   
4178256   2022               Iceland       826    91020     0.010   
4330419   2022                  Iran       826    91020  1063.810   
4425032   2022               Ireland       826    91020    31.797   
4856318   2022                 Italy       826    91020    36.038   
5459263   2022               Lebanon       826    91020     0.369   
6700144   2022           Netherlands       826    91020     2.296   
7357742   2022                Poland       826    91020    19.559   
7524477   2022              Portugal       826    91020     2.870   
7665235   2022               Romania       826    91020    20.472   
8197273   2022                 India       826    91020    67.383   
8833236   2022          South Africa       826    91020     0.355   
9154176   2022                 Spain       826    91020  2634.433   
9354287   2022                Sweden       826    91020     2.274   
9974808   2022  United Arab Emirates       826    91020    95.593   
10348338  2022               Türkiye       826    91020     2.855   

               quantity  
5197              1.110  
446153            0.039  
477852               NA  
801746            0.682  
1016615           0.038  
1452321           0.063  
2010462           2.080  
2595440           0.006  
3247517           0.981  
3684513           0.037  
3822296           0.159  
4156318              NA  
4178256              NA  
4330419          10.991  
4425032           0.043  
4856318           0.028  
5459263           0.001  
6700144           0.038  
7357742           0.064  
7524477           0.495  
7665235           0.006  
8197273           5.971  
8833236           0.103  
9154176          19.930  
9354287           0.058  
9974808           0.329  
10348338          0.245

Raw export data into UK 2021, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [102]:
data_saffron_uk_2021

year                 exporter  importer  product     value  \
5990      2021              Afghanistan       826    91020    65.425   
446950    2021                  Austria       826    91020     0.604   
803353    2021                  Belgium       826    91020     1.340   
1016857   2021                   Brazil       826    91020     1.454   
2426640   2021                  Czechia       826    91020     0.708   
2616642   2021                  Denmark       826    91020     0.067   
2707975   2021                 Ethiopia       826    91020     0.505   
2775802   2021                  Estonia       826    91020     0.055   
3265972   2021                   France       826    91020   273.021   
3314448   2021                  Georgia       826    91020     0.366   
3707802   2021                  Germany       826    91020    32.985   
3844902   2021                   Greece       826    91020    17.407   
4192018   2021                  Hungary       826    91020     0.007   
4377744   2021                     Iran       826    91020   847.352   
4473078   2021                  Ireland       826    91020    57.890   
4908628   2021                    Italy       826    91020    50.917   
5525643   2021                  Lebanon       826    91020     0.367   
6757118   2021              Netherlands       826    91020    42.444   
7413956   2021                   Poland       826    91020    15.960   
7580166   2021                 Portugal       826    91020    13.083   
8320747   2021                    India       826    91020    65.180   
8587015   2021                 Slovakia       826    91020     0.019   
9287748   2021                    Spain       826    91020  1635.003   
9493245   2021                   Sweden       826    91020     9.328   
10115797  2021     United Arab Emirates       826    91020     8.788   
10483948  2021                  Türkiye       826    91020     2.929   
11030293  2021  United Rep. of Tanzania       826    91020     0.010   
11432574  2021                      USA       826    91020     3.624   

               quantity  
5990              3.805  
446950               NA  
803353            0.002  
1016857           0.704  
2426640           0.026  
2616642           0.001  
2707975           0.450  
2775802           0.001  
3265972           6.835  
3314448           0.015  
3707802           0.034  
3844902           0.020  
4192018              NA  
4377744           3.444  
4473078           8.894  
4908628           0.195  
5525643           0.001  
6757118           5.067  
7413956           0.113  
7580166           1.317  
8320747           6.326  
8587015           0.002  
9287748           9.432  
9493245           0.190  
10115797          0.053  
10483948          0.211  
11030293          0.001  
11432574          0.091

Raw export data into UK 2020, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [103]:
data_saffron_uk_2020

year              exporter  importer  product     value  \
4522      2020           Afghanistan       826    91020    93.026   
416448    2020               Austria       826    91020     0.379   
756807    2020               Belgium       826    91020     2.119   
957853    2020                Brazil       826    91020     0.267   
1925246   2020                 China       826    91020    67.591   
2304215   2020               Czechia       826    91020     1.145   
3107328   2020                France       826    91020   179.776   
3547679   2020               Germany       826    91020     7.012   
3576253   2020                 Ghana       826    91020     1.145   
3676432   2020                Greece       826    91020    24.320   
4010986   2020               Hungary       826    91020     0.065   
4184128   2020                  Iran       826    91020   320.420   
4268626   2020               Ireland       826    91020    12.084   
4689399   2020                 Italy       826    91020    48.192   
6440988   2020           Netherlands       826    91020    21.703   
7079932   2020                Poland       826    91020     9.353   
7237533   2020              Portugal       826    91020    22.844   
7366648   2020               Romania       826    91020     0.772   
7908166   2020                 India       826    91020    14.247   
8283839   2020              Viet Nam       826    91020     0.875   
8833754   2020                 Spain       826    91020  2126.049   
9027392   2020                Sweden       826    91020     0.298   
9618798   2020  United Arab Emirates       826    91020    11.289   
10901266  2020               Uruguay       826    91020     0.193   

               quantity  
4522             11.177  
416448            0.001  
756807            0.141  
957853            0.030  
1925246          43.200  
2304215           0.001  
3107328           1.566  
3547679           0.004  
3576253           0.500  
3676432           0.033  
4010986           0.005  
4184128           0.663  
4268626           3.227  
4689399           1.197  
6440988           3.341  
7079932           0.019  
7237533           7.755  
7366648           0.012  
7908166           6.080  
8283839           0.001  
8833754           8.792  
9027392           0.001  
9618798           0.025  
10901266          0.029

Raw export data into UK 2019, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [104]:
data_saffron_uk_2019

year              exporter  importer  product     value  \
4037     2019           Afghanistan       826    91020    16.360   
428395   2019               Austria       826    91020     0.111   
777080   2019               Belgium       826    91020     0.649   
980079   2019                Brazil       826    91020     4.920   
1415691  2019             Sri Lanka       826    91020    19.530   
1972818  2019                 China       826    91020   442.190   
2359594  2019               Czechia       826    91020     0.540   
3180887  2019                France       826    91020   308.228   
3629571  2019               Germany       826    91020    10.847   
3766737  2019                Greece       826    91020    12.149   
4114564  2019               Hungary       826    91020     0.061   
4295122  2019                  Iran       826    91020   472.360   
4378684  2019               Ireland       826    91020    18.141   
4810576  2019                 Italy       826    91020    69.315   
6222947  2019               Morocco       826    91020     2.600   
6234994  2019            Mozambique       826    91020     0.029   
6608339  2019           Netherlands       826    91020    13.801   
7265929  2019                Poland       826    91020    38.643   
7425168  2019              Portugal       826    91020    26.341   
7555247  2019               Romania       826    91020     0.376   
8112418  2019                 India       826    91020    13.483   
9061907  2019                 Spain       826    91020  2484.830   
9259335  2019                Sweden       826    91020     0.529   
9872320  2019  United Arab Emirates       826    91020    13.176   

              quantity  
4037             2.056  
428395              NA  
777080           0.037  
980079           0.047  
1415691         11.520  
1972818             NA  
2359594          0.079  
3180887          0.286  
3629571          0.006  
3766737          0.014  
4114564             NA  
4295122          0.377  
4378684          2.392  
4810576          1.081  
6222947          0.001  
6234994          0.017  
6608339          2.502  
7265929          3.877  
7425168             NA  
7555247          0.029  
8112418          0.614  
9061907         67.672  
9259335          0.001  
9872320          0.013

Raw export data into UK 2018, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [105]:
data_saffron_uk_2018

year     exporter  importer  product     value       quantity
3600     2018  Afghanistan       826    91020     1.301          0.039
414655   2018      Austria       826    91020     0.250             NA
749450   2018      Belgium       826    91020     0.233          0.022
937744   2018       Brazil       826    91020     0.035          0.006
1878304  2018        China       826    91020   536.375         18.219
2259608  2018      Czechia       826    91020     0.783          0.101
3054927  2018       France       826    91020   256.304          0.219
3493692  2018      Germany       826    91020     9.099          0.061
3624698  2018       Greece       826    91020    28.161          0.018
3959419  2018      Hungary       826    91020     0.057             NA
4136550  2018         Iran       826    91020   579.807          1.632
4217374  2018      Ireland       826    91020    30.961          3.176
4640208  2018        Italy       826    91020   114.857          1.955
5214430  2018      Lebanon       826    91020     1.849          0.570
6002108  2018      Morocco       826    91020     2.051          0.001
6372916  2018  Netherlands       826    91020     2.348          0.162
6998246  2018       Poland       826    91020    33.159          0.724
7152364  2018     Portugal       826    91020    35.460          4.474
7279016  2018      Romania       826    91020     0.013             NA
7816419  2018        India       826    91020    25.254          0.023
8742769  2018        Spain       826    91020  2730.246          3.522
8935133  2018       Sweden       826    91020     1.727          0.001

Raw export data into UK 2017, value in 1000 usd, quantity in tons... importer 826 is uk, code 91020 is saffron

In [106]:
data_saffron_uk_2017

year     exporter  importer  product     value       quantity
2763     2017  Afghanistan       826    91020     5.447          0.006
384100   2017      Austria       826    91020     0.008             NA
701855   2017      Belgium       826    91020   129.175         45.176
1765556  2017        China       826    91020   664.238          0.096
2128785  2017      Czechia       826    91020     0.027          0.003
2889820  2017       France       826    91020   244.398          0.432
3316473  2017      Germany       826    91020     1.160          0.001
3432367  2017       Greece       826    91020    13.599          0.022
3746388  2017      Hungary       826    91020     0.064             NA
3911568  2017         Iran       826    91020   699.112          2.976
3988104  2017      Ireland       826    91020    23.393          4.204
4396334  2017        Italy       826    91020    88.333          2.807
4925324  2017      Lebanon       826    91020     1.961          0.822
5389443  2017       Mexico       826    91020     7.437          0.767
6000895  2017  Netherlands       826    91020   260.747         18.950
6110365  2017      Nigeria       826    91020     0.251          4.550
6587059  2017       Poland       826    91020     7.606          0.089
6732711  2017     Portugal       826    91020    46.242          3.530
6847500  2017      Romania       826    91020     0.012          0.001
7335652  2017        India       826    91020     3.230          0.016
8144619  2017        Spain       826    91020  3126.319         30.892
8331367  2017       Sweden       826    91020     1.407          0.001
9881670  2017          USA       826    91020     3.403          0.430

In [113]:
def calculate_average_price_per_kg(df):
    df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
    df['average_per_kg'] = (df['value'] * 1000) / (df['quantity'] * 1000)

    result_df = df[['exporter', 'value', 'quantity', 'average_per_kg']]
    result_df = result_df.sort_values(by='average_per_kg', ascending=False)
    
    return result_df

In [115]:
data_saffron_uk_2022_df = calculate_average_price_per_kg(data_saffron_uk_2022)
data_saffron_uk_2021_df = calculate_average_price_per_kg(data_saffron_uk_2021)
data_saffron_uk_2020_df = calculate_average_price_per_kg(data_saffron_uk_2020)
data_saffron_uk_2019_df = calculate_average_price_per_kg(data_saffron_uk_2019)
data_saffron_uk_2018_df = calculate_average_price_per_kg(data_saffron_uk_2018)
data_saffron_uk_2017_df = calculate_average_price_per_kg(data_saffron_uk_2017)

average per kg of imported saffron in the uk, 2022, descending by average

In [116]:
data_saffron_uk_2022_df

exporter     value  quantity  average_per_kg
7665235                Romania    20.472     0.006     3412.000000
4856318                  Italy    36.038     0.028     1287.071429
3822296                 Greece   132.593     0.159      833.918239
3684513                Germany    29.832     0.037      806.270270
4425032                Ireland    31.797     0.043      739.465116
446153                 Austria    24.543     0.039      629.307692
3247517                 France   605.306     0.981      617.029562
2595440                Denmark     2.797     0.006      466.166667
5459263                Lebanon     0.369     0.001      369.000000
7357742                 Poland    19.559     0.064      305.609375
9974808   United Arab Emirates    95.593     0.329      290.556231
5197               Afghanistan   216.225     1.110      194.797297
9154176                  Spain  2634.433    19.930      132.184295
4330419                   Iran  1063.810    10.991       96.789191
6700144            Netherlands     2.296     0.038       60.421053
9354287                 Sweden     2.274     0.058       39.206897
1016615                 Brazil     0.468     0.038       12.315789
10348338               Türkiye     2.855     0.245       11.653061
8197273                  India    67.383     5.971       11.285044
7524477               Portugal     2.870     0.495        5.797980
1452321              Sri Lanka     0.276     0.063        4.380952
801746                 Belgium     2.891     0.682        4.239003
8833236           South Africa     0.355     0.103        3.446602
2010462                  China     5.842     2.080        2.808654
477852                 Bahrain     0.064       NaN             NaN
4156318                Hungary     0.006       NaN             NaN
4178256                Iceland     0.010       NaN             NaN

average per kg of imported saffron in the uk, 2021, descending by average

In [117]:
data_saffron_uk_2021_df

exporter     value  quantity  average_per_kg
3707802                   Germany    32.985     0.034      970.147059
3844902                    Greece    17.407     0.020      870.350000
803353                    Belgium     1.340     0.002      670.000000
5525643                   Lebanon     0.367     0.001      367.000000
4908628                     Italy    50.917     0.195      261.112821
4377744                      Iran   847.352     3.444      246.037166
9287748                     Spain  1635.003     9.432      173.346374
10115797     United Arab Emirates     8.788     0.053      165.811321
7413956                    Poland    15.960     0.113      141.238938
2616642                   Denmark     0.067     0.001       67.000000
2775802                   Estonia     0.055     0.001       55.000000
9493245                    Sweden     9.328     0.190       49.094737
3265972                    France   273.021     6.835       39.944550
11432574                      USA     3.624     0.091       39.824176
2426640                   Czechia     0.708     0.026       27.230769
3314448                   Georgia     0.366     0.015       24.400000
5990                  Afghanistan    65.425     3.805       17.194481
10483948                  Türkiye     2.929     0.211       13.881517
8320747                     India    65.180     6.326       10.303509
11030293  United Rep. of Tanzania     0.010     0.001       10.000000
7580166                  Portugal    13.083     1.317        9.933941
8587015                  Slovakia     0.019     0.002        9.500000
6757118               Netherlands    42.444     5.067        8.376554
4473078                   Ireland    57.890     8.894        6.508882
1016857                    Brazil     1.454     0.704        2.065341
2707975                  Ethiopia     0.505     0.450        1.122222
446950                    Austria     0.604       NaN             NaN
4192018                   Hungary     0.007       NaN             NaN

average per kg of imported saffron in the uk, 2020, descending by average

In [118]:
data_saffron_uk_2020_df

exporter     value  quantity  average_per_kg
3547679                Germany     7.012     0.004     1753.000000
2304215                Czechia     1.145     0.001     1145.000000
8283839               Viet Nam     0.875     0.001      875.000000
3676432                 Greece    24.320     0.033      736.969697
7079932                 Poland     9.353     0.019      492.263158
4184128                   Iran   320.420     0.663      483.288084
9618798   United Arab Emirates    11.289     0.025      451.560000
416448                 Austria     0.379     0.001      379.000000
9027392                 Sweden     0.298     0.001      298.000000
8833754                  Spain  2126.049     8.792      241.816310
3107328                 France   179.776     1.566      114.799489
7366648                Romania     0.772     0.012       64.333333
4689399                  Italy    48.192     1.197       40.260652
756807                 Belgium     2.119     0.141       15.028369
4010986                Hungary     0.065     0.005       13.000000
957853                  Brazil     0.267     0.030        8.900000
4522               Afghanistan    93.026    11.177        8.322985
10901266               Uruguay     0.193     0.029        6.655172
6440988            Netherlands    21.703     3.341        6.495959
4268626                Ireland    12.084     3.227        3.744654
7237533               Portugal    22.844     7.755        2.945712
7908166                  India    14.247     6.080        2.343257
3576253                  Ghana     1.145     0.500        2.290000
1925246                  China    67.591    43.200        1.564606

average per kg of imported saffron in the uk, 2019, descending by average

In [119]:
data_saffron_uk_2019_df

exporter     value  quantity  average_per_kg
6222947               Morocco     2.600     0.001     2600.000000
3629571               Germany    10.847     0.006     1807.833333
4295122                  Iran   472.360     0.377     1252.944297
3180887                France   308.228     0.286     1077.720280
9872320  United Arab Emirates    13.176     0.013     1013.538462
3766737                Greece    12.149     0.014      867.785714
9259335                Sweden     0.529     0.001      529.000000
980079                 Brazil     4.920     0.047      104.680851
4810576                 Italy    69.315     1.081       64.121184
9061907                 Spain  2484.830    67.672       36.718732
8112418                 India    13.483     0.614       21.959283
777080                Belgium     0.649     0.037       17.540541
7555247               Romania     0.376     0.029       12.965517
7265929                Poland    38.643     3.877        9.967243
4037              Afghanistan    16.360     2.056        7.957198
4378684               Ireland    18.141     2.392        7.584030
2359594               Czechia     0.540     0.079        6.835443
6608339           Netherlands    13.801     2.502        5.515987
6234994            Mozambique     0.029     0.017        1.705882
1415691             Sri Lanka    19.530    11.520        1.695312
428395                Austria     0.111       NaN             NaN
1972818                 China   442.190       NaN             NaN
4114564               Hungary     0.061       NaN             NaN
7425168              Portugal    26.341       NaN             NaN

average per kg of imported saffron in the uk, 2018, descending by average

In [120]:
data_saffron_uk_2018_df

exporter     value  quantity  average_per_kg
6002108      Morocco     2.051     0.001     2051.000000
8935133       Sweden     1.727     0.001     1727.000000
3624698       Greece    28.161     0.018     1564.500000
3054927       France   256.304     0.219     1170.337900
7816419        India    25.254     0.023     1098.000000
8742769        Spain  2730.246     3.522      775.197615
4136550         Iran   579.807     1.632      355.273897
3493692      Germany     9.099     0.061      149.163934
4640208        Italy   114.857     1.955       58.750384
6998246       Poland    33.159     0.724       45.799724
3600     Afghanistan     1.301     0.039       33.358974
1878304        China   536.375    18.219       29.440419
6372916  Netherlands     2.348     0.162       14.493827
749450       Belgium     0.233     0.022       10.590909
4217374      Ireland    30.961     3.176        9.748426
7152364     Portugal    35.460     4.474        7.925793
2259608      Czechia     0.783     0.101        7.752475
937744        Brazil     0.035     0.006        5.833333
5214430      Lebanon     1.849     0.570        3.243860
414655       Austria     0.250       NaN             NaN
3959419      Hungary     0.057       NaN             NaN
7279016      Romania     0.013       NaN             NaN

average per kg of imported saffron in the uk, 2017, descending by average

In [121]:
data_saffron_uk_2017_df

exporter     value  quantity  average_per_kg
1765556        China   664.238     0.096     6919.145833
8331367       Sweden     1.407     0.001     1407.000000
3316473      Germany     1.160     0.001     1160.000000
2763     Afghanistan     5.447     0.006      907.833333
3432367       Greece    13.599     0.022      618.136364
2889820       France   244.398     0.432      565.736111
3911568         Iran   699.112     2.976      234.916667
7335652        India     3.230     0.016      201.875000
8144619        Spain  3126.319    30.892      101.201573
6587059       Poland     7.606     0.089       85.460674
4396334        Italy    88.333     2.807       31.468828
6000895  Netherlands   260.747    18.950       13.759736
6732711     Portugal    46.242     3.530       13.099717
6847500      Romania     0.012     0.001       12.000000
5389443       Mexico     7.437     0.767        9.696219
2128785      Czechia     0.027     0.003        9.000000
9881670          USA     3.403     0.430        7.913953
3988104      Ireland    23.393     4.204        5.564462
701855       Belgium   129.175    45.176        2.859372
4925324      Lebanon     1.961     0.822        2.385645
6110365      Nigeria     0.251     4.550        0.055165
384100       Austria     0.008       NaN             NaN
3746388      Hungary     0.064       NaN             NaN